### ISSUE TITLE
Online documentation is outdated (https://pearllists.herokuapp.com)

### ISSUE THREAD

**Issue by andela-bmakinwa** [andela-oesho/pearllists#32]
Changes were made to the functionality of the service. However, the documentation online was not updated to that effect.
For example, when a user creates an account, the user is logged in and the response sent contains the user's token. This change is not reflected in the documentation.

**Comment by andela-oesho** [comment]
@andela-bmakinwa correction noted, the documentation has been updated.Here is a screenshot below.
![image](https://cloud.githubusercontent.com/assets/14160244/15140293/578dfb16-1692-11e6-83b5-e6b73e33d36f.png)
