### ISSUE TITLE
Specs

### ISSUE THREAD

**Issue by andela-bmakinwa** [andela-oesho/pearllists#36]
🔴 **CRITICAL** 
So many issues were found while I was going through your spec files.

- Tests do not cater for situations when no authorization token is passed

- Test descriptions and messages are not appropriate and don't pass the right information

- Models not tested

- The existence of unused files and folders in spec. For example `controllers`.

Please go through your specs carefully line by line and clean up accordingly. Review the spec messages and update with the appropriate messages.

**Comment by andela-oesho** [comment]
@andela-bmakinwa all corrections noted and taken care of, changes have now been merged with master.
