### ISSUE TITLE
Having a central place for your messages

### ISSUE THREAD

**Issue by andela-bmakinwa** [andela-oesho/pearllists#48]
In your codebase, you used error messages and success messages to indicate success or failure of certain actions. It is good practice to have a central source for these messages.
Having a central place would aid maintainability. In essence, one does not have to change a particular message in all the files that message has been used and can just change it from one source.

**Comment by andela-oesho** [comment]
@andela-bmakinwa correction noted and fixed. The changes have been updated with master branch.
